version: "3"
services:
        app:
                build: .
                ports:
                        - "8080:8080"
                volumes:
                        - /tmp:/tmp
                environment:
                        - ARBITRARY_VARIABLE=arbitrary_value
                restart: always
                container_name: flask_app

